# Generated by Django 4.2.2 on 2023-07-15 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LFTBcertificates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='LFTBcourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='LFTBuserDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField()),
                ('author', models.BooleanField()),
                ('level', models.IntegerField()),
                ('pro', models.BooleanField()),
                ('certificates', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.lftbcertificates')),
                ('courses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.lftbcourses')),
            ],
        ),
    ]
