# Generated by Django 4.2.2 on 2023-07-15 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lftbuserdb',
            name='certificates',
        ),
        migrations.RemoveField(
            model_name='lftbuserdb',
            name='courses',
        ),
        migrations.AddField(
            model_name='lftbuserdb',
            name='certificates',
            field=models.ManyToManyField(to='sites.lftbcertificates'),
        ),
        migrations.AddField(
            model_name='lftbuserdb',
            name='courses',
            field=models.ManyToManyField(to='sites.lftbcourses'),
        ),
    ]
