# Generated by Django 4.2.2 on 2023-07-15 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_remove_lftbuserdb_certificates_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LFTBcourses',
            new_name='certificatesT',
        ),
        migrations.RenameModel(
            old_name='LFTBcertificates',
            new_name='coursesT',
        ),
        migrations.RenameModel(
            old_name='LFTBuserDB',
            new_name='userT',
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificatesE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.certificatest')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.coursest')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.usert')),
            ],
        ),
    ]
