# Generated by Django 4.2.2 on 2023-07-22 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0007_alter_usert_certificates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usert',
            name='certificates',
        ),
        migrations.AddField(
            model_name='usert',
            name='certificates_temp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.certificatest'),
        ),
    ]
