# Generated by Django 4.2.2 on 2023-07-22 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0008_remove_usert_certificates_usert_certificates_temp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usert',
            name='certificates_temp',
        ),
        migrations.RemoveField(
            model_name='usert',
            name='confirm',
        ),
        migrations.AddField(
            model_name='usert',
            name='certificates',
            field=models.ManyToManyField(to='sites.certificatest'),
        ),
        migrations.AlterField(
            model_name='usert',
            name='author',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='usert',
            name='courses',
            field=models.ManyToManyField(to='sites.coursest'),
        ),
        migrations.AlterField(
            model_name='usert',
            name='level',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='usert',
            name='pro',
            field=models.BooleanField(),
        ),
    ]
