# Generated by Django 4.2.2 on 2023-07-22 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0010_remove_usert_certificates_usert_confirm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usert',
            name='certificates',
            field=models.CharField(default=None),
        ),
        migrations.RemoveField(
            model_name='usert',
            name='courses',
        ),
        migrations.DeleteModel(
            name='Enrollment',
        ),
        migrations.AddField(
            model_name='usert',
            name='courses',
            field=models.CharField(default=None),
        ),
    ]
