# Generated by Django 4.2.2 on 2023-07-22 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0011_usert_certificates_remove_usert_courses_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='certificatesT',
        ),
        migrations.DeleteModel(
            name='coursesT',
        ),
    ]
