# Generated by Django 4.2.2 on 2023-07-22 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0012_delete_certificatest_delete_coursest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usert',
            name='certificates',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='usert',
            name='courses',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='usert',
            name='password',
            field=models.CharField(max_length=20),
        ),
    ]
