# Generated by Django 4.2.2 on 2023-07-22 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0013_alter_usert_certificates_alter_usert_courses_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='userT',
            new_name='sites_usert',
        ),
    ]
