# Generated by Django 4.2.2 on 2023-07-22 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0014_rename_usert_sites_usert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sites_usert',
            name='certificates',
            field=models.CharField(default=None),
        ),
    ]
