# Generated by Django 4.2.2 on 2023-07-22 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0015_alter_sites_usert_certificates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sites_usert',
            name='certificates',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
