# Generated by Django 4.2.2 on 2023-07-22 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0016_alter_sites_usert_certificates'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_certificates', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='sites_usert',
            name='certificates',
        ),
        migrations.AddField(
            model_name='sites_usert',
            name='certificates',
            field=models.ManyToManyField(to='sites.certificate'),
        ),
    ]
