name: Deploy


on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/
        with:
      - run: python manage.py runserver
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}